import { WorldCard } from '../worldCard.js';
import { Ocean } from '../ocean.js';

let eastCoast = new WorldCard (
    [
    `      OOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `      OOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `     OOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `     OOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `     OOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `     OOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `    OOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `    OOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `    OOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `    OOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `     OOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `     OOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `      OOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `       OOOOOOOOOOOOOOOOOOOOOOOOO`,
    `       OOOOOOOOOOOOOOOOOOOOOOOOO`,
    `        OOOOOOOOOOOOOOOOOOOOOOOO`,
    `        OOOOOOOOOOOOOOOOOOOOOOOO`,
    `        OOOOOOOOOOOOOOOOOOOOOOOO`,
    `        OOOOOOOOOOOOOOOOOOOOOOOO`,
    `       OOOOOOOOOOOOOOOOOOOOOOOOO`,
    `       OOOOOOOOOOOOOOOOOOOOOOOOO`,
    `       OOOOOOOOOOOOOOOOOOOOOOOOO`,
    `       OOOOOOOOOOOOOOOOOOOOOOOOO`,
    `      OOOOOOOOOOOOOOOOOOOOOOOOOO`,
    ],
    {
        "O": Ocean,
    }
)

export { eastCoast }