import { WorldCard } from '../worldCard.js';
import { Ocean } from '../ocean.js';
import { Grass } from '../grass/grass.js';

let northwestCoast = new WorldCard (
    [
        `          OOOOOOOOOOOOOOOOOOOOOO`,
        `       OOOOOOOOOOOOOOOOOOOOOOOOO`,
        `     OOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `  OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        ` OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        ` OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        ` OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOO   `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  `,
    ],
    {
        " ": Grass,
        "O": Ocean,
    }
)

northwestCoast.noRotate = true

export { northwestCoast }