import { WorldCard } from '../worldCard.js';
import { Ocean } from '../ocean.js';
import { Ore } from '../ore.js';

let northeastCoast = new WorldCard (
    [
    `OOOOOOOOOOOOOOOOOOOOOOO         `,
    `OOOOOOOOOOOOOOOOOOOOOOOOOOO     `,
    `OOOOOOOOOOOOOOOOOOOOOOOOOOOOO   `,
    `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  `,
    `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  `,
    `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO `,
    `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO `,
    `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO `,
    `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `OOOOOOOOO    OOOOOOOOOOOOOOOOOOO`,
    `OOOOOOOO     $ OOOOOOOOOOOOOOOOO`,
    `OOOOOOOO    $ $  OOOOOOOOOOOOOOO`,
    `OO   OO  *        OOOOOOOOOOOOOO`,
    `O             $OOOOOOOOOOOOOOOOO`,
    `    $      $  OOOOOOOOOOOOOOOOOO`,
    `   $        $ OOOOOOOOOOOOOOOOOO`,
    `           $   OOOOOOOOOOOOOOOOO`,
    `            $ $OOOOOOOOOOOOOOOOO`,
    `       OOOOO $OOO OOOOOOOOOOOOOO`,
    ],
    {
        "O": Ocean,
        "$": Ore,
    }
)

northeastCoast.noRotate = true

export { northeastCoast }