import { WorldCard } from '../worldCard.js';
import { Ocean } from '../ocean.js';

let southeastCoast = new WorldCard (
    [
        `    OOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `     OOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `     O OOOOOOOOOOOOOOOOOOOOOOOOO`,
        `   OOOOOOOOOOOOOO OOOOOOOOOOOOOO`,
        `   OOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `   OOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `    OOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `   OOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOO OOOOOOOOO`,
        `OOOOOOOOOOO OOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    ],
    {
        "O": Ocean,
    }
)

export { southeastCoast }