import { WorldCard } from '../worldCard.js';
import { Ocean } from '../ocean.js';

let southwestCoast = new WorldCard (
    [
        `OOOOOOOOOOOO            OOOOO   `,
        `OOOOOOOOOO           OOOOOOOO   `,
        `OOOOOOOOOO       OOOOOOOOOOO    `,
        `OOOOOOOOOO     OOOOOOOOOOOO     `,
        `OOOOOOOOOOO   OOOOOOOOOOOOw      `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOO      `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOO      `,
        `OOOOOOOOOOOOOOOOOOOOOOOOO       `,
        `OOOOOOOOOOOOOOOOOOOOOOOOO       `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOO     `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    ],
    {
        "O": Ocean,
    }
)

export { southwestCoast }