import { WorldCard } from '../worldCard.js';
import { Ocean } from '../ocean.js';

let southwestCoast = new WorldCard (
    [
        `OOOOOOOOOOOOOOOOOOOO            `,
        `OOOOOOOOOOOOOOOOOOOOOOOOO       `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOO    `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOO   `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        ` OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        ` OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        ` OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `  OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `  OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `   OOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `     OOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `        OOOOOOOOOOOOOOOOOOOOOOOO`,
    ],
    {
        "O": Ocean,
    }
)

southwestCoast.noRotate = true

export { southwestCoast }