import { WorldCard } from '../worldCard.js';
import { Ocean } from '../ocean.js';

let westCoast = new WorldCard (
    [
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOO   `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOO   `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOO   `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOO     `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOO     `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOO      `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOO     `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOO    `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOO    `,
        `OOOOOOOOOOOOOOOOOOOOOOOOOOOOO   `,
    ],
    {
        "O": Ocean,
    }
)

westCoast.rotateOnlyVertically = true

export { westCoast }